### ISSUE TITLE
How to resize the Simulator window?

### ISSUE THREAD

**Issue by laventura** [udacity/Bosch-Challenge#2]
I accidentally full-screened the Bosch simulator on Macbook. 

The simulator will not resize to a smaller size now. That is, cannot grab the right-lower or left-lower corners (or infact any edges) to drag the window smaller. 

Mac OS 10.11.x

Is there anyway to resize it??

Thanks!

**Comment by jwdunn1** [comment]
Move mouse pointer to top of screen to activate menu bar and then click the green button. Works on my Mac for both maxed window and for non-windowed option.

**Comment by laventura** [comment]
Thanks - that's the first thing I tried - but it doesn't resize to a smaller size :-/ 
It's a bit frustrating because the mouse cannot grab any edge or corner either. :-(

**Comment by baumanab** [comment]
Sorry for the late reply.  This sounds frustrating.  Was this resolved?

**Comment by mvirgo** [comment]
No responses in four months, so closing.
